title: GUAC
description: The site for everyone's favorite software supply chain knowledge graph
theme: just-the-docs

url: https://guac.sh
logo: "/assets/images/guac.png"

aux_links:
  GUAC Repo: https://github.com/guacsec/guac
